databases:
  - name: kultur-db
    databaseName: kultur
    user: kultur_user
    plan: free

services:
  - type: web
    name: kultur-backend
    env: python
    rootDir: backend
    buildCommand: pip install . && pip install psycopg2-binary bcrypt==4.0.1
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        fromDatabase:
          name: kultur-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "https://kultur-frontend-jljp.onrender.com"
      - key: ENVIRONMENT
        value: "production"

  - type: web
    name: kultur-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_API_BASE_URL
        value: "https://kultur-backend.onrender.com"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
